### ISSUE TITLE
Update all examples to use AIController

### ISSUE THREAD

**Issue by edbeeching** [edbeeching/godot_rl_agents_examples#4]

**Comment by metinc** [comment]
I could take care of this.

**Comment by metinc** [comment]
Thanks, I will update the plugin to the latest version in all examples in this process.

**Comment by Ivan-267** [comment]
Thanks for offering to tackle this. Let us know if you need any help with it.

I have just remembered that one of my envs is using a slightly modified plugin, so in case or AirHockey we shouldn't change the plugin at this point.

For future reference, I changed this line: https://github.com/edbeeching/godot_rl_agents_examples/blob/bbe18a44eac8f5576f2b746c9f484ce4a488dfed/examples/AirHockey/addons/godot_rl_agents/controller/ai_controller_3d.gd#L50 

This dependency can be removed at some point by adding the change to the AIController override instead as I did in my later env https://github.com/edbeeching/godot_rl_agents_examples/blob/bbe18a44eac8f5576f2b746c9f484ce4a488dfed/examples/3DCarParking/scenes/car/CarAIController.gd#L62

3DCarParking itself is new so it may already be using the newest plugin, but I think it should work fine if the plugin was replaced.
