### ISSUE TITLE
FPS project crashing when launched

### ISSUE THREAD

**Issue by alexpalms** [edbeeching/godot_rl_agents_examples#5]
**Description:**
The FPS game is not able to run, it crashes at this line: https://github.com/edbeeching/godot_rl_agents_examples/blob/5e064c9b7ca619fdee3e69daa16b8c5b31760bb2/examples/FPS/main.gd#L21

![image](https://github.com/edbeeching/godot_rl_agents_examples/assets/13517266/1955f7c0-fe7c-46c5-bc93-d3190510c34c)

with the following output messages:
![image](https://github.com/edbeeching/godot_rl_agents_examples/assets/13517266/82405e85-3304-4987-af00-5b5cfe88566e)

**Expected behavior:**
Launch the selected game

**Steps to reproduce:**
- Download this repo
- Launch Godot
- Import FPS godot project file
- Click run button (or F5)

**Environment info:**
- Windows 10
- Godot 4.0.1
- Using miniconda virtual env system

**Additional info:**
- Also tried to first run `gdrl` before launching the game
- Also looked for docs, especially as the introductory tutorial on the RingPong game (https://huggingface.co/learn/deep-rl-course/unitbonus3/godotrl?fw=pt) mentiones it saying:

"_This can be a great benefit on more complex environments, like the **multi-player FPS we will learn about in the next chapter.**_"

but was not able to find the mentioned chapter.

**Comment by edbeeching** [comment]
Hi thanks for reporting this issue. It appears that some of the IK nodes were changed between Godot 4 beta 14 and Godot 4 stable.
I just updated the example, there is still something funky going on with the animations, but it should run now. Let me know of any further issues.

**Comment by alexpalms** [comment]
Pulling solved the issue, thanks.
